apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-service
  namespace: microservices-study
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing-service
  template:
    metadata:
      labels:
        app: billing-service
    spec:
      containers:
        - name: billing-service
          image: billing-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 4007
            - containerPort: 3010
          env:
            - name: NODE_ENV
              value: "development"
            - name: PORT
              value: "3010"
            - name: TCP_PORT
              value: "4007"
            - name: HTTP_PORT
              value: "3005"
            - name: DB_HOST
              value: "postgres-billing"
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: DB_NAME
              value: "billing_db"
            - name: DB_LOGGING
              value: "true"
            - name: DB_SSL
              value: "false"
            - name: RABBITMQ_URL
              value: "amqp://admin:admin@rabbitmq:5672"
            - name: RABBITMQ_QUEUE
              value: "billing_queue"
            - name: RABBITMQ_EXCHANGE
              value: "logiflow.events"
            - name: RABBITMQ_PREFETCH_COUNT
              value: "1"
            - name: IVA_PERCENTAGE
              value: "12"
            - name: INVOICE_PREFIX
              value: "F"
---
apiVersion: v1
kind: Service
metadata:
  name: billing-service
  namespace: microservices-study
spec:
  selector:
    app: billing-service
  ports:
    - protocol: TCP
      port: 4007
      targetPort: 4007
      name: tcp
    - protocol: TCP
      port: 3010
      targetPort: 3010
      name: http
