apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-service
  namespace: microservices-study
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleet-service
  template:
    metadata:
      labels:
        app: fleet-service
    spec:
      containers:
        - name: fleet-service
          image: fleet-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 4005
          env:
            - name: NODE_ENV
              value: "development"
            - name: FLEET_PORT
              value: "4005"
            - name: TCP_PORT
              value: "4005"
            - name: DB_HOST
              value: "postgres-fleet"
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: DB_DATABASE
              value: "fleet_db"
            - name: DB_SYNC
              value: "true"
            - name: DB_LOGGING
              value: "false"
            - name: RABBITMQ_URL
              value: "amqp://admin:admin@rabbitmq:5672"
---
apiVersion: v1
kind: Service
metadata:
  name: fleet-service
  namespace: microservices-study
spec:
  selector:
    app: fleet-service
  ports:
    - protocol: TCP
      port: 4005
      targetPort: 4005
