apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-inventory
  namespace: microservices-study
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-inventory
  template:
    metadata:
      labels:
        app: postgres-inventory
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: inventory-db-config
            - secretRef:
                name: inventory-db-secret
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-inventory-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-inventory
  namespace: microservices-study
spec:
  selector:
    app: postgres-inventory
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-inventory-pvc
  namespace: microservices-study
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-db-config
  namespace: microservices-study
data:
  POSTGRES_DB: inventory_db
  POSTGRES_USER: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: inventory-db-secret
  namespace: microservices-study
type: Opaque
stringData:
  POSTGRES_PASSWORD: postgres
