apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-tracking
  namespace: microservices-study
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-tracking
  template:
    metadata:
      labels:
        app: postgres-tracking
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: tracking-db-config
            - secretRef:
                name: tracking-db-secret
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-tracking-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-tracking
  namespace: microservices-study
spec:
  selector:
    app: postgres-tracking
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-tracking-pvc
  namespace: microservices-study
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tracking-db-config
  namespace: microservices-study
data:
  POSTGRES_DB: tracking_db
  POSTGRES_USER: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: tracking-db-secret
  namespace: microservices-study
type: Opaque
stringData:
  POSTGRES_PASSWORD: postgres
