apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: logiflow
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: logiflow
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: admin
  RABBITMQ_DEFAULT_PASS: admin
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: logiflow
type: Opaque
stringData:
  JWT_SECRET: your-super-secret-jwt-key-change-in-production
  BETTER_AUTH_SECRET: your-super-secret-better-auth-key-change-in-production
---
apiVersion: v1
kind: Secret
metadata:
  name: mailjet-secret
  namespace: logiflow
type: Opaque
stringData:
  MAILJET_API_KEY: c7ae23f384a7066d2617ebc19d5bb1ad
  MAILJET_API_SECRET: 2a2714c65ede7d89ddbd8101b6c9cf39
  MAILJET_SENDER_EMAIL: josuelsoy12@gmail.com
  MAILJET_SENDER_NAME: LogiFlow
