apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-service
  namespace: logiflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleet-service
  template:
    metadata:
      labels:
        app: fleet-service
    spec:
      containers:
      - name: fleet-service
        image: logiflow/fleet-service:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3003
          name: tcp
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: logiflow-config
              key: FLEET_SERVICE_PORT
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: logiflow-config
              key: NODE_ENV
        - name: TCP_HOST
          valueFrom:
            configMapKeyRef:
              name: logiflow-config
              key: TCP_HOST
        - name: TCP_PORT
          valueFrom:
            configMapKeyRef:
              name: logiflow-config
              key: FLEET_TCP_PORT
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: logiflow-config
              key: FLEET_DATABASE_URL
        - name: RABBITMQ_URL
          valueFrom:
            configMapKeyRef:
              name: logiflow-config
              key: RABBITMQ_URL
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RABBITMQ_DEFAULT_USER
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RABBITMQ_DEFAULT_PASS
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: fleet-service
  namespace: logiflow
spec:
  type: ClusterIP
  ports:
  - port: 3003
    targetPort: 3003
    protocol: TCP
    name: http
  - port: 4005
    targetPort: 4005
    protocol: TCP
    name: tcp
  selector:
    app: fleet-service
